import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import './globals.css'
import type { FC, ReactNode } from 'react'

const geistSans = Geist({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: ReactNode
}

const RootLayout: FC<Readonly<RootLayoutProps>> = ({ children }) => {
  return (
    <html
      lang="en"
      className={`${geistSans.className} h-full antialiased`}
    >
      <body>{children}</body>
    </html>
  )
}

export default RootLayout
